FROM philippvk/sdslab:latest

#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends wget unzip g++ libboost-system-dev libboost-filesystem-dev graphviz doxygen libtinfo-dev zlib1g-dev verilator autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
